// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: helmchart.proto

package helmchart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetSystem int32  `protobuf:"varint,1,opt,name=targetSystem,proto3" json:"targetSystem,omitempty"`
	RepoName     string `protobuf:"bytes,2,opt,name=repoName,proto3" json:"repoName,omitempty"`
	ChartName    string `protobuf:"bytes,3,opt,name=chartName,proto3" json:"chartName,omitempty"`
	ChartVersion string `protobuf:"bytes,4,opt,name=chartVersion,proto3" json:"chartVersion,omitempty"`
}

func (x *ChartRequest) Reset() {
	*x = ChartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helmchart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartRequest) ProtoMessage() {}

func (x *ChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helmchart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartRequest.ProtoReflect.Descriptor instead.
func (*ChartRequest) Descriptor() ([]byte, []int) {
	return file_helmchart_proto_rawDescGZIP(), []int{0}
}

func (x *ChartRequest) GetTargetSystem() int32 {
	if x != nil {
		return x.TargetSystem
	}
	return 0
}

func (x *ChartRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *ChartRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *ChartRequest) GetChartVersion() string {
	if x != nil {
		return x.ChartVersion
	}
	return ""
}

type ChartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChartBytes []byte `protobuf:"bytes,2,opt,name=chartBytes,proto3" json:"chartBytes,omitempty"`
}

func (x *ChartResponse) Reset() {
	*x = ChartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helmchart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartResponse) ProtoMessage() {}

func (x *ChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helmchart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartResponse.ProtoReflect.Descriptor instead.
func (*ChartResponse) Descriptor() ([]byte, []int) {
	return file_helmchart_proto_rawDescGZIP(), []int{1}
}

func (x *ChartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChartResponse) GetChartBytes() []byte {
	if x != nil {
		return x.ChartBytes
	}
	return nil
}

var File_helmchart_proto protoreflect.FileDescriptor

var file_helmchart_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x65, 0x6c, 0x6d, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x61,
	0x72, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x0d, 0x43, 0x68, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x74, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x74, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x32, 0x47, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x48, 0x65, 0x6c, 0x6d, 0x43,
	0x68, 0x61, 0x72, 0x74, 0x12, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x2f, 0x5a,
	0x2d, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x78, 0x7a, 0x79, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helmchart_proto_rawDescOnce sync.Once
	file_helmchart_proto_rawDescData = file_helmchart_proto_rawDesc
)

func file_helmchart_proto_rawDescGZIP() []byte {
	file_helmchart_proto_rawDescOnce.Do(func() {
		file_helmchart_proto_rawDescData = protoimpl.X.CompressGZIP(file_helmchart_proto_rawDescData)
	})
	return file_helmchart_proto_rawDescData
}

var file_helmchart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helmchart_proto_goTypes = []any{
	(*ChartRequest)(nil),  // 0: rpc.ChartRequest
	(*ChartResponse)(nil), // 1: rpc.ChartResponse
}
var file_helmchart_proto_depIdxs = []int32{
	0, // 0: rpc.ChartManager.GetHelmChart:input_type -> rpc.ChartRequest
	1, // 1: rpc.ChartManager.GetHelmChart:output_type -> rpc.ChartResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helmchart_proto_init() }
func file_helmchart_proto_init() {
	if File_helmchart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helmchart_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ChartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helmchart_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ChartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helmchart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helmchart_proto_goTypes,
		DependencyIndexes: file_helmchart_proto_depIdxs,
		MessageInfos:      file_helmchart_proto_msgTypes,
	}.Build()
	File_helmchart_proto = out.File
	file_helmchart_proto_rawDesc = nil
	file_helmchart_proto_goTypes = nil
	file_helmchart_proto_depIdxs = nil
}
