// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: helmchart.proto

package helmchart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChartManager_GetHelmChart_FullMethodName = "/rpc.ChartManager/GetHelmChart"
)

// ChartManagerClient is the client API for ChartManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChartManagerClient interface {
	GetHelmChart(ctx context.Context, in *ChartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChartResponse], error)
}

type chartManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewChartManagerClient(cc grpc.ClientConnInterface) ChartManagerClient {
	return &chartManagerClient{cc}
}

func (c *chartManagerClient) GetHelmChart(ctx context.Context, in *ChartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChartResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChartManager_ServiceDesc.Streams[0], ChartManager_GetHelmChart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChartRequest, ChartResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChartManager_GetHelmChartClient = grpc.ServerStreamingClient[ChartResponse]

// ChartManagerServer is the server API for ChartManager service.
// All implementations must embed UnimplementedChartManagerServer
// for forward compatibility.
type ChartManagerServer interface {
	GetHelmChart(*ChartRequest, grpc.ServerStreamingServer[ChartResponse]) error
	mustEmbedUnimplementedChartManagerServer()
}

// UnimplementedChartManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChartManagerServer struct{}

func (UnimplementedChartManagerServer) GetHelmChart(*ChartRequest, grpc.ServerStreamingServer[ChartResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetHelmChart not implemented")
}
func (UnimplementedChartManagerServer) mustEmbedUnimplementedChartManagerServer() {}
func (UnimplementedChartManagerServer) testEmbeddedByValue()                      {}

// UnsafeChartManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChartManagerServer will
// result in compilation errors.
type UnsafeChartManagerServer interface {
	mustEmbedUnimplementedChartManagerServer()
}

func RegisterChartManagerServer(s grpc.ServiceRegistrar, srv ChartManagerServer) {
	// If the following call pancis, it indicates UnimplementedChartManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChartManager_ServiceDesc, srv)
}

func _ChartManager_GetHelmChart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChartRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChartManagerServer).GetHelmChart(m, &grpc.GenericServerStream[ChartRequest, ChartResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChartManager_GetHelmChartServer = grpc.ServerStreamingServer[ChartResponse]

// ChartManager_ServiceDesc is the grpc.ServiceDesc for ChartManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChartManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ChartManager",
	HandlerType: (*ChartManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHelmChart",
			Handler:       _ChartManager_GetHelmChart_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helmchart.proto",
}
